version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8001:8001
    links:
      - mongo
  mongo:
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles

  mongo-shell:
    image: mongo:3.4
    links:
      - mongo
    command: mongo mongodb://mongo:27017/task-manager
    stdin_open: true
    tty: true
